name: 'm release'
description: 'execute the release command'
runs:
  using: 'composite'
  steps:
    - name: github release
      run: |
        m github release --owner "$M_OWNER" --repo "$M_REPO" --version "$M_TAG" | m json
      shell: bash
