name: 'm ensure-pnpm'
description: 'ensure that pnpm is installed and cache the store'
inputs:
  pnpm-version:
    description: pnpm version to install
    default: latest
    required: false
runs:
  using: 'composite'
  steps:
    - name: ensure pnpm
      id: pnpm-cache
      shell: bash
      run: ${GITHUB_ACTION_PATH}/ensure-pnpm.sh ${{ inputs.pnpm-version }}

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache.outputs.store-path }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm-store-
