name: M

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jmlopez-rod/m-devcontainer
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      env:
        PYTHONPATH: ./packages/python
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPMJS_TOKEN: ${{ secrets.NPMJS_TOKEN }}
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: PATH setup
        run: |
          echo "./packages/bash/lib" >> $GITHUB_PATH
      - name: Checks
        run: ./m/scripts/checks/ci.sh
      - name: Publish
        run: ./m/scripts/publish.sh
