name: M

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  PYTHONPATH: ./packages/python
  FORCE_COLOR: 1
  MYPY_FORCE_COLOR: 1
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # setup:
  #   runs-on: ubuntu-22.04
  #   strategy:
  #     matrix:
  #       py-ver: [py310-uv]
  #   container:
  #     image: ghcr.io/jmlopez-rod/m-devcontainer-${{ matrix.py-ver }}:latest
  #     credentials:
  #       username: ${{ github.actor }}
  #       password: ${{ secrets.GITHUB_TOKEN }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Install
  #       run: |
  #         uv venv /opt/uv/m
  #         . "$VIRTUAL_ENV/bin/activate"
  #         uv sync

  #     - name: Cache uv
  #       uses: actions/cache@v4
  #       with:
  #         path: /opt/uv
  #         key: uv-${{ matrix.py-ver }}-${{ hashFiles('**/uv.lock') }}

  tests:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        py-ver: [py310-uv]
    container:
      image: ghcr.io/jmlopez-rod/m-devcontainer-${{ matrix.py-ver }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.10'

      - name: run tests
        run: |
          uv sync
          ./packages/python/tests/run.sh

  flake8:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/jmlopez-rod/m-devcontainer-py310-uv:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.10'

      - name: Install
        run: uv sync --all-groups

      - name: lint src
        shell: bash
        run: |
          m ci celt -t flake8 -c @allowed_errors.json < <(flake8 packages/python/m)

      - name: lint tests
        shell: bash
        run: |
          m ci celt -t flake8 -c @allowed_errors_tests.json < <(flake8 packages/python/tests --config .flake8-tests)

      - name: lint docs
        shell: bash
        run: flake8 packages/web/docs

  mypy:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/jmlopez-rod/m-devcontainer-py310-uv:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.10'

      - name: Install
        run: uv sync --all-groups

      - name: src
        run: |
          mypy ./packages/python/m

      - name: tests
        run: |
          mypy ./packages/python/tests

      - name: docs
        run: |
          mypy ./packages/web/docs

  docs:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/jmlopez-rod/m-devcontainer-py310-uv:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.10'

      - name: Install
        run: uv sync --all-groups

      - name: build
        run: |
          export PATH=$VIRTUAL_ENV/bin:$PATH
          cd packages/web && mkdocs build

  prettier:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/jmlopez-rod/m-devcontainer-py310-uv:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: pnpm install
        run: |
          pnpm install

      - name: prettier
        shell: bash
        run: |
          pnpm exec prettier -c .

  build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/jmlopez-rod/m-devcontainer-py310-uv:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      m-is-release: ${{ steps.build.outputs.m-is-release }}
      m-tag: ${{ steps.build.outputs.m-tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.10'

      - name: Install
        run: uv sync --all-groups

      - name: Build
        id: build
        run: |
          ./m/scripts/build.sh

      - name: Save build
        uses: actions/cache/save@v4
        with:
          path: ./.stage-pypi
          key: build-${{ github.sha }}

  release:
    needs: [build, tests, flake8, mypy, prettier]
    if: ${{ needs.build.outputs.m-is-release == 'True' }}
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/jmlopez-rod/m-devcontainer-py310-uv:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        M_TAG: ${{ needs.build.outputs.m-tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: uv sync --all-groups

      - name: Restore build
        uses: actions/cache/restore@v4
        with:
          path: ./.stage-pypi
          key: build-${{ github.sha }}

      - name: Release
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          ./m/scripts/publish.sh
