name: M

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ./packages/python
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPMJS_TOKEN: ${{ secrets.NPMJS_TOKEN }}
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: PATH setup
        run: |
          echo "./packages/bash/lib" >> $GITHUB_PATH
          pip3 install wemake-python-styleguide coverage mypy pylint build twine
      - name: Checks
        run: |
          ./m/scripts/checks/ci.sh
      - name: Publish
        run: |
          ./m/scripts/publish.sh
